import type { Campaign, CampaignId, Mission } from '../types';
import { validateScenarioData } from './validate';

const singaporeMissions: Mission[] = [
  {
    id: 'SG-01',
    title: 'Practice, then protect',
    date: '2026-10-09',
    description: 'A fictional coastal practice area introduces the deck sling, a freshwater pickup and one controlled release in calm conditions. Put water on the marked grass fire and return to RSS Persistence.',
    lesson: 'The 5,000 L bucket changes the aircraft’s response. Hold a steady hover over the marked lake zone, release at low height, then land within the ship’s marked operating area.',
    seed: 91001,
    ship: { x: -7, z: -3, label: 'RSS Persistence · gameplay start' },
    shipHeading: 0.025,
    lake: { x: 220, z: 1485, label: 'Fictional practice lake · gameplay only', radius: 180 },
    fire: { x: 317, z: 1823, label: 'Practice fire · fictional', radius: 85 },
    wind: { x: 1.2, z: -0.6 },
    requiredDrops: 1,
    peat: false,
    protectedLabel: 'Fictional practice huts',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 330, endMinutes: 480 },
  },
  {
    id: 'SG-02',
    title: 'Reed-line containment',
    date: '2026-10-09',
    description: 'A fast surface fire is moving through fictional reeds on the edge of the Sembuluh-inspired sector in a light crosswind. Make two useful drops before it reaches the authored lakeside homes.',
    lesson: 'Approach into the light crosswind and favour a compact, accurate footprint over a high-volume miss.',
    seed: 91002,
    ship: { x: 13, z: 4, label: 'RSS Persistence · gameplay start' },
    shipHeading: -0.06,
    lake: { x: 220, z: 1485, label: 'Danau Sembuluh reference sector · gameplay refill zone', radius: 180 },
    fire: { x: 513, z: 1714, label: 'Fictional reed-line fire', radius: 105 },
    wind: { x: 3.4, z: -0.9 },
    requiredDrops: 2,
    peat: false,
    protectedLabel: 'Fictional lakeside homes',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 480, endMinutes: 720 },
  },
  {
    id: 'SG-03',
    title: 'Hold the peat edge',
    date: '2026-10-09',
    description: 'Low smoke hangs over an authored peat margin. Suppress the visible flame, then make a follow-up pass so residual heat does not threaten the fictional village access track.',
    lesson: 'Peat can keep smouldering after the surface flame falls. Give a suppressed patch time and water to secure.',
    seed: 91003,
    ship: { x: -12, z: -8, label: 'RSS Persistence · gameplay start' },
    shipHeading: 0.08,
    lake: { x: 220, z: 1485, label: 'Danau Sembuluh reference sector · gameplay refill zone', radius: 180 },
    fire: { x: -50, z: 1770, label: 'Fictional peat-edge fire', radius: 125 },
    wind: { x: -3.7, z: 1.3 },
    requiredDrops: 3,
    peat: true,
    protectedLabel: 'Fictional village access track',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 720, endMinutes: 1050 },
  },
  {
    id: 'SG-04',
    title: 'Protect the fish pens',
    date: '2026-10-09',
    description: 'A broken line of canopy and scrub fires is approaching fictional community fish pens in a steady crosswind. Place two drops across the hot sector while keeping clear of boats and working water.',
    lesson: 'Choose an approach that accounts for crosswind drift and leave a clear turn back toward the lake.',
    seed: 91004,
    ship: { x: 8, z: 11, label: 'RSS Persistence · gameplay start' },
    shipHeading: -0.035,
    lake: { x: 220, z: 1485, label: 'Danau Sembuluh reference sector · gameplay refill zone', radius: 180 },
    fire: { x: 595, z: 1516, label: 'Fictional canopy and scrub fire', radius: 110 },
    wind: { x: 4.6, z: 0.7 },
    requiredDrops: 2,
    peat: false,
    protectedLabel: 'Fictional community fish pens',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1050, endMinutes: 1110 },
  },
  {
    id: 'SG-05',
    title: 'Jetty visibility window',
    date: '2026-10-09',
    description: 'An authored fire is pushing smoke across a fictional community jetty. Visibility opens briefly between haze bands and a shifting breeze; complete three measured drops while keeping the jetty clear.',
    lesson: 'Use visual references near the target, keep the lake approach simple and do not press on when the target is obscured.',
    seed: 91005,
    ship: { x: -16, z: 2, label: 'RSS Persistence · gameplay start' },
    shipHeading: 0.055,
    lake: { x: 220, z: 1485, label: 'Danau Sembuluh reference sector · gameplay refill zone', radius: 180 },
    fire: { x: -135, z: 1344, label: 'Fictional haze-sector fire', radius: 115 },
    wind: { x: -2.6, z: 2.8 },
    requiredDrops: 3,
    peat: false,
    protectedLabel: 'Fictional community jetty',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1110, endMinutes: 1200 },
  },
  {
    id: 'SG-06',
    title: 'Secure the forest buffer',
    date: '2026-10-09',
    description: 'After a dry, gusty period, a fictional fire has reached the forest buffer. Knock down the surface spread and revisit the warm edge before returning to the ship.',
    lesson: 'A good first drop slows spread; a deliberate follow-up secures the edge and protects the authored habitat boundary.',
    seed: 91006,
    ship: { x: 10, z: -5, label: 'RSS Persistence · gameplay start' },
    shipHeading: -0.075,
    lake: { x: 220, z: 1485, label: 'Danau Sembuluh reference sector · gameplay refill zone', radius: 180 },
    fire: { x: 473, z: 1180, label: 'Fictional forest-buffer fire', radius: 130 },
    wind: { x: 1.0, z: -4.1 },
    requiredDrops: 3,
    peat: true,
    protectedLabel: 'Fictional forest buffer',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1200, endMinutes: 1770 },
  },
];

const japanMissions: Mission[] = [
  {
    id: 'JP-01',
    title: 'Practice shore handling',
    date: '2026-09-23',
    description: 'A calm, labelled fictional practice sector teaches a clean ferry to the shore pad, bucket installation, one lake-to-fire cycle, unrigging and ship recovery. This is practice, not a recorded sortie.',
    lesson: 'At the pad, the bucket is a separate supported object until the crew attaches it. Confirm the rig is secured before departure and leave it ashore for the clean return ferry.',
    seed: 92001,
    ship: { x: -5, z: 3, label: 'JS Kunisaki · gameplay start' },
    shipHeading: -0.03,
    shore: { x: 120, z: 400, label: 'Fictional practice shore handling pad' },
    lake: { x: 335, z: 1429, label: 'Fictional practice lake · gameplay only', radius: 166 },
    fire: { x: 409, z: 1755, label: 'Practice fire · fictional', radius: 85 },
    wind: { x: 1.5, z: 0.4 },
    requiredDrops: 1,
    peat: false,
    protectedLabel: 'Fictional practice huts',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 330, endMinutes: 480 },
  },
  {
    id: 'JP-02',
    title: 'Ketapang fringe',
    date: '2026-09-24',
    description: 'A reconstructed local-sector sortie starts with the bucket at the Rahadi Oesman support pad. In light coastal haze, make two accurate drops on an authored scrub fire threatening fictional homes, then complete the clean return ferry.',
    lesson: 'Treat the airport and its bucket-handling sequence as a gameplay reconstruction. The documented support report does not establish this exact sequence for every real sortie.',
    seed: 92002,
    ship: { x: 11, z: -6, label: 'JS Kunisaki · gameplay start' },
    shipHeading: 0.065,
    shore: { x: 120, z: 400, label: 'Rahadi Oesman support pad · representative gameplay waypoint' },
    lake: { x: 335, z: 1429, label: 'Ketapang refill lake · reconstructed freshwater gameplay zone', radius: 166 },
    fire: { x: 601, z: 1662, label: 'Fictional Ketapang fringe fire', radius: 105 },
    wind: { x: 2.8, z: 0.9 },
    requiredDrops: 2,
    peat: false,
    protectedLabel: 'Fictional Ketapang village-edge homes',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 480, endMinutes: 720 },
  },
  {
    id: 'JP-03',
    title: 'Watch the smoke lane',
    date: '2026-09-25',
    description: 'Visibility varies in smoke over an authored peat and scrub sector. Suppress the flame front and make a follow-up drop before residual heat spreads toward fictional roadside homes.',
    lesson: 'Smoke limits what you can see. Keep the return leg simple and use the debrief map to review your drop footprint.',
    seed: 92003,
    ship: { x: -13, z: 7, label: 'JS Kunisaki · gameplay start' },
    shipHeading: -0.055,
    shore: { x: 120, z: 400, label: 'Rahadi Oesman support pad · representative gameplay waypoint' },
    lake: { x: 335, z: 1429, label: 'Ketapang refill lake · reconstructed freshwater gameplay zone', radius: 166 },
    fire: { x: 74, z: 1696, label: 'Fictional peat and scrub fire', radius: 125 },
    wind: { x: -3.1, z: 0.6 },
    requiredDrops: 3,
    peat: true,
    protectedLabel: 'Fictional roadside homes',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 720, endMinutes: 1050 },
  },
  {
    id: 'JP-04',
    title: 'Crosswind turn',
    date: '2026-09-26',
    description: 'A gusty crosswind pushes a fictional fire toward a forested drainage line. Build a stable approach and place two drops inside the authored containment sector.',
    lesson: 'Allow for ground drift on both the lake approach and the drop; do not carry a rushed correction into the sling.',
    seed: 92004,
    ship: { x: 7, z: 10, label: 'JS Kunisaki · gameplay start' },
    shipHeading: 0.04,
    shore: { x: 120, z: 400, label: 'Rahadi Oesman support pad · representative gameplay waypoint' },
    lake: { x: 335, z: 1429, label: 'Ketapang refill lake · reconstructed freshwater gameplay zone', radius: 166 },
    fire: { x: 580, z: 1744, label: 'Fictional drainage-line fire', radius: 110 },
    wind: { x: 4.2, z: -2.0 },
    requiredDrops: 2,
    peat: false,
    protectedLabel: 'Fictional forest drainage buffer',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1050, endMinutes: 1110 },
  },
  {
    id: 'JP-05',
    title: 'Secure the blackened edge',
    date: '2026-09-28',
    description: 'Under a light, variable breeze, an authored peat patch has lost its visible flame but retains heat. Revisit the edge with three measured drops so the fictional community access road stays open.',
    lesson: 'A surface-suppressed fire is not necessarily secure. Check the map and make the required follow-up water placement.',
    seed: 92005,
    ship: { x: -10, z: -9, label: 'JS Kunisaki · gameplay start' },
    shipHeading: -0.08,
    shore: { x: 120, z: 400, label: 'Rahadi Oesman support pad · representative gameplay waypoint' },
    lake: { x: 335, z: 1429, label: 'Ketapang refill lake · reconstructed freshwater gameplay zone', radius: 166 },
    fire: { x: -20, z: 1329, label: 'Fictional blackened peat edge', radius: 120 },
    wind: { x: -1.8, z: -3.3 },
    requiredDrops: 3,
    peat: true,
    protectedLabel: 'Fictional community access road',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1110, endMinutes: 1200 },
  },
  {
    id: 'JP-06',
    title: 'Last light containment',
    date: '2026-09-29',
    description: 'For this reconstructed closing sortie, clear a small fictional fire from the edge of an authored settlement buffer in clear evening conditions before the operation’s documented end date. The target is game fiction, not a reported incident.',
    lesson: 'Prioritise the threatened edge, confirm the fire is secured, then recover to Kunisaki with fuel in reserve.',
    seed: 92006,
    ship: { x: 15, z: 1, label: 'JS Kunisaki · gameplay start' },
    shipHeading: 0.07,
    shore: { x: 120, z: 400, label: 'Rahadi Oesman support pad · representative gameplay waypoint' },
    lake: { x: 335, z: 1429, label: 'Ketapang refill lake · reconstructed freshwater gameplay zone', radius: 166 },
    fire: { x: 615, z: 1214, label: 'Fictional settlement-buffer fire', radius: 105 },
    wind: { x: 0.9, z: 3.5 },
    requiredDrops: 2,
    peat: false,
    protectedLabel: 'Fictional settlement buffer',
    durationTargetSec: 300,
    timeOfDay: { startMinutes: 1200, endMinutes: 1770 },
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'sg_fictional_2026_10',
    name: 'RSAF Deployment',
    subtitle: 'Fictional campaign · October 2026',
    operator: 'Republic of Singapore Air Force',
    aircraft: 'RSAF CH-47F',
    shipName: 'RSS Persistence · Endurance-class LST (209)',
    evidenceMode: 'fictional_inspired',
    context: 'A fictional humanitarian mission inspired by Indonesia’s October 2026 wildfire and haze conditions. Fires, priorities, routes, ship station, refill permissions and clearances are authored for gameplay. Danau Sembuluh is a geographic and freshwater-setting reference; no in-game point is asserted to be an approved real helicopter refill site. The ship-origin mission coordinates are a compressed local gameplay layout in metres, not geographic coordinates or a claimed real route distance.',
    missions: singaporeMissions,
    mass: { baseline: 11148, crew: 600, rig: 250, fuel: 3100, maxGross: 22680 },
    color: 0x55b9c4,
    shipLength: 141,
    shipWidth: 21,
  },
  {
    id: 'jp_ketapang_2026_09',
    name: 'JSDF Deployment',
    subtitle: 'Based on a real deployment · September 2026',
    operator: 'Japan Ground Self-Defense Force',
    aircraft: 'JGSDF CH-47 · represented by a CH-47JA preset',
    shipName: 'JS Kunisaki · Ōsumi-class LST (LST-4003)',
    evidenceMode: 'documented_operation_reconstruction',
    context: 'Based on Japan’s real September 2026 firefighting deployment to Indonesia. Playable missions, exact routes, ship positions, weather and freshwater refill lakes are reconstructed for the game. Official sources establish the deployed CH-47 family, Kunisaki, Ketapang and operation dates; they do not identify the exact dip site, fire polygons, ship anchorage or every sortie sequence. A CH-47JA is a representative gameplay preset, not an asserted deployed serial/configuration. The ship-origin mission coordinates are a compressed local gameplay layout in metres, not geographic coordinates or a claimed real route distance.',
    missions: japanMissions,
    mass: { baseline: 11500, crew: 600, rig: 250, fuel: 3100, maxGross: 22680 },
    color: 0xe67858,
    shipLength: 178,
    shipWidth: 25.8,
  },
];

export function getCampaign(id: CampaignId): Campaign | undefined {
  return campaigns.find((campaign) => campaign.id === id);
}

export function getMission(campaignId: CampaignId, missionId: string): Mission | undefined {
  return getCampaign(campaignId)?.missions.find((mission) => mission.id === missionId);
}

export function validateContent(): string[] {
  return validateScenarioData(campaigns);
}
